export default CarData = [
    {
        registration_No: '1',
        car_Name: 'Gli',
        make_Name: 'BMW',
        modal_Number: 'Gli 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Civic X',
        make_Name: 'Honda',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Civic X',
        make_Name: 'Honda',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Gli',
        make_Name: 'Hyundai',
        modal_Number: 'Gli 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Civic X',
        make_Name: 'Mazda',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Gli',
        make_Name: 'Hyundai',
        modal_Number: 'Gli 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Civic X',
        make_Name: 'Mazda',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Gli',
        make_Name: 'Mercedes',
        modal_Number: 'Gli 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Mazda',
        make_Name: 'Suzukie',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Mercedes',
        make_Name: 'Tesla',
        modal_Number: 'Gli 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
    {
        registration_No: '1',
        car_Name: 'Civic X',
        make_Name: 'Toyota',
        modal_Number: 'Civic 2019',
        owner_Name: 'Awais',
        color: 'white',
    },
];