export default CarData = [
  {
    registration_No: 1,
    car_Name: 'BMW X6',
    make_Name: 'BMW',
    modal_Number: '2022',
    owner_Name: 'Jake',
    color: 'Blue',
  },
  {
    registration_No: 2,
    car_Name: 'Civic',
    make_Name: 'Honda',
    modal_Number: '2022',
    owner_Name: 'Andrew',
    color: 'White',
  },
  {
    registration_No: 3,
    car_Name: 'HB20',
    make_Name: 'Hyundai',
    modal_Number: '2019',
    owner_Name: 'Hassan',
    color: 'Black',
  },
  {
    registration_No: 4,
    car_Name: 'Mazdaspeed6',
    make_Name: 'Mazda',
    modal_Number: '2007',
    owner_Name: 'Jason',
    color: 'Black',
  },
  {
    registration_No: 5,
    car_Name: 'GLA SUV',
    make_Name: 'Mercedes',
    modal_Number: '2023',
    owner_Name: 'Awais',
    color: 'White',
  },
  {
    registration_No: 6,
    car_Name: 'Swift',
    make_Name: 'Suzukie',
    modal_Number: '2016',
    owner_Name: 'Ahmed',
    color: 'Blue',
  },
  {
    registration_No: 7,
    car_Name: 'Model S',
    make_Name: 'Tesla',
    modal_Number: '2022',
    owner_Name: 'Taqi',
    color: 'White',
  },
  {
    registration_No: 8,
    car_Name: 'Lexus',
    make_Name: 'Toyota',
    modal_Number: '2016',
    owner_Name: 'Sasha',
    color: 'Black',
  },
  {
    registration_No: 9,
    car_Name: 'Hino',
    make_Name: 'Toyota',
    modal_Number: '2012',
    owner_Name: 'Rose',
    color: 'Blue',
  },
  {
    registration_No: 10,
    car_Name: 'Civic X',
    make_Name: 'Honda',
    modal_Number: '2021',
    owner_Name: 'Rose',
    color: 'Blue',
  },
];
